# SonarQube project configuration
sonar.projectKey=Ex13_A_Exercise13A_Python_Project
sonar.projectName=Exercise13A_Python_Project
sonar.projectVersion=1.0

# Branch information
sonar.branch.name=main

# Source code location
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Language
sonar.language=py
sonar.python.version=3

# Exclusions
sonar.exclusions=**/venv/**,**/env/**,**/__pycache__/**,**/.git/**
